language: java
jdk:
    - openjdk8

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8   

script:
    - mvn clean install
    - mvn deploy jib:build -P deploy-docker
    
